### ISSUE TITLE
Export Image Assets

### ISSUE THREAD

**Issue by IICorzyII** [inker8/xd-plugin#1]
In addition to export SVG can you include more options for exporting image assets?

**Comment by zaaack** [comment]
@IICorzyII  Yes, I'm thinking about this. Currently, Inker8 can only export SVG icons and download images. If you select multiple nodes, it will merge them to single one SVG, this is useful for icons that are not properly grouped, but not suitable for download multiple icons at a time. I'll add an export dialog for more custom options.

**Comment by zaaack** [comment]
@IICorzyII New plugin wizard is done, you can try it via download the plugin from GitHub, market version is under review, thanks.
