### ISSUE TITLE
background-color isn't displaying

### ISSUE THREAD

**Issue by patitdude123** [inker8/xd-plugin#3]
Windows 10 (XD)
CSS: background-color or color isn't displaying in Edge v17

**Comment by zaaack** [comment]
@patitdude123 ~~Can you provide a minimal reproducible .xd file via drag it into the comment input box?~~

Well, I reproduced this bug in Edge, looks some API doesn't work expectedly on Edge, I only tested on the latest Chrome. You can use Chrome currently, I'll see what I can do.

**Comment by zaaack** [comment]
@patitdude123 The fixed version(v1.0.3) has just submitted to review. If you can't wait you can download directly from the GitHub: https://github.com/inker8/xd-plugin/raw/master/inker8-xd.xdx 

Thanks!
